name: Node.js CI
on:
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: install dependencies
        run: yarn install --frozen-lockfile --check-files
        env:
          CI: true

  run_unit_tests:
    needs: install_dependencies
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: run unit testing
        run: yarn test:unit
      - name: Archive unit coverage
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            build/reports
        env:
          CI: true

  run_e2e_tests:
    needs: install_dependencies
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: build docker
        run: yarn docker:build
      - name: run docker
        run: yarn docker:start
      - name: run postman testing
        run: yarn test:e2e
      - name: stop docker
        run: yarn docker:stop
      - name: Archive unit coverage
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            build/reports
        env:
          CI: true

  run_mutation_testing:
    needs: install_dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Install
        run: |
         yarn install
      - name: Run Stryker
        run: yarn test:unit:mutate:ci
