name: Node.js CI
on:
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: install dependencies
        run: yarn install --frozen-lockfile --check-files
        env:
          CI: true

  run_unit_tests:
    needs: install_dependencies
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: run tests:unit
        run: yarn test
      - name: Archive unit coverage
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            build/reports
        env:
          CI: true
